[package]
name = "dimensional_analyser"
version = "0.2.0"
edition = "2024"
description = "Runtime dimensional analysis and unit-aware quantities for Rust"
readme = "README.md"
license = "MIT"
repository = "https://github.com/Taro9000/dimensional_analyser"
documentation = "https://docs.rs/dimensional_analyser"
keywords = ["dimensions", "units", "physics", "quantity", "conversion"]
categories = ["science", "mathematics"]

[lints.clippy]
pedantic = { level = "warn", priority = -1}
nursery = { level = "warn", priority = -1}
unwrap_unused = "deny"

[dependencies]

[features]
default = []
debug-print = []