[package]
name = "dimensional_analyser"
version = "0.1.0"
edition = "2024"

[lints.clippy]
pedantic = { level = "warn", priority = -1}
nursery = { level = "warn", priority = -1}
unwrap_unused = "deny"

[dependencies]

[features]
default = ["debug-print", "sci-notation"]
debug-print = []
sci-notation = []